[package]
name = "qrono-bench"
version = "0.1.0"
authors = ["Chris Thunes <cthunes@brewtab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
futures = "0.3"
bytes = "0.6"

[dependencies.tokio-util]
version = "0.5"
#features = ["codec"]

[dependencies.tokio]
version = "0.3"
features = ["full"]

[dependencies.redis-async]
version = "0.7"

#[dependencies.redis]
#version = "*"
#features = ["aio", "tokio-comp"]
